#!/usr/bin/env bash
#
# Полная установка SSTP-сервера (accel-ppp) на чистой Ubuntu 22.04/24.04.
# Идемпотентен: повторный запуск обновляет конфиг, но не пересобирает accel-ppp,
# если бинарь уже есть.
#
# Использование:
#   sudo bash setup-sstp.sh                      # дефолтные параметры
#   sudo SSTP_PORT=14942 SSTP_USER=keenetic bash setup-sstp.sh
#
# Параметры через env:
#   SSTP_PORT      порт TCP (default: 14942)
#   SSTP_USER      имя пользователя SSTP (default: keenetic)
#   SSTP_PASS      пароль (default: генерится случайно)
#   SSTP_NET       подсеть PPP-туннеля (default: 10.27.0.0/24)
#   SSTP_GW_IP     IP шлюза в туннеле (default: 10.27.0.1)
#   SSTP_POOL      диапазон пула клиентов (default: 10.27.0.2-100)
#   SSTP_CN        Common Name в TLS-сертификате (default: внешний IP)
#   SSTP_WAN_IF    WAN-интерфейс для NAT (default: автоопределение)

set -euo pipefail

SSTP_PORT="${SSTP_PORT:-14942}"
SSTP_USER="${SSTP_USER:-keenetic}"
SSTP_PASS="${SSTP_PASS:-$(openssl rand -hex 8)}"
SSTP_NET="${SSTP_NET:-10.27.0.0/24}"
SSTP_GW_IP="${SSTP_GW_IP:-10.27.0.1}"
SSTP_POOL="${SSTP_POOL:-10.27.0.2-100}"
SSTP_WAN_IF="${SSTP_WAN_IF:-$(ip route show default | awk '/default/ {print $5; exit}')}"
SSTP_CN="${SSTP_CN:-$(curl -fsS https://api.ipify.org || hostname -I | awk '{print $1}')}"

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"

log() { echo -e "\n\033[1;36m[sstp]\033[0m $*"; }

require_root() {
  if [ "$EUID" -ne 0 ]; then
    echo "Run as root (sudo)."; exit 1
  fi
}

install_build_deps() {
  log "Installing build dependencies..."
  DEBIAN_FRONTEND=noninteractive apt-get update -qq
  DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
    cmake build-essential gcc g++ git \
    libssl-dev libpcre2-dev libcap-dev \
    ppp openssl iptables curl
}

build_accel_ppp() {
  if [ -x /usr/sbin/accel-pppd ]; then
    log "accel-pppd already installed, skipping build."
    return
  fi
  log "Building accel-ppp from source..."
  mkdir -p /usr/local/src
  cd /usr/local/src
  if [ ! -d accel-ppp ]; then
    git clone --depth 1 https://github.com/accel-ppp/accel-ppp.git
  fi
  cd accel-ppp
  rm -rf build
  mkdir build && cd build
  cmake \
    -DBUILD_IPOE_DRIVER=FALSE \
    -DBUILD_VLAN_MON_DRIVER=FALSE \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DLUA=FALSE \
    -DKDIR=no \
    .. >/tmp/accel-cmake.log 2>&1
  make -j"$(nproc)" install >/tmp/accel-build.log 2>&1
  log "accel-pppd installed: $(/usr/sbin/accel-pppd -V 2>&1 | head -1 || echo OK)"
}

generate_cert() {
  log "Generating self-signed TLS cert (CN=$SSTP_CN)..."
  mkdir -p /etc/accel-ppp/sstp
  cd /etc/accel-ppp/sstp
  if [ -f server.crt ] && [ -f server.key ]; then
    log "TLS cert already exists, keeping."
  else
    openssl req -new -newkey rsa:2048 -days 3650 -nodes -x509 \
      -subj "/C=RU/ST=Moscow/L=Moscow/O=ovpn/CN=$SSTP_CN" \
      -addext "subjectAltName=IP:$SSTP_CN" \
      -keyout server.key -out server.crt 2>/dev/null
    chmod 600 server.key
  fi
  cat server.crt server.key > server.pem
  chmod 600 server.pem
}

write_config() {
  log "Writing /etc/accel-ppp.conf..."
  install -d -m 755 /etc/accel-ppp
  install -d -m 755 /var/log/accel-ppp

  cat > /etc/accel-ppp.conf <<EOF
# Generated by setup-sstp.sh
[modules]
log_file
sstp
auth_mschap_v2
auth_mschap_v1
auth_chap_md5
auth_pap
chap-secrets
ippool
sigchld
pppd_compat

[core]
log-error=/var/log/accel-ppp/core.log
thread-count=2

[log]
log-file=/var/log/accel-ppp/accel-ppp.log
log-emerg=/var/log/accel-ppp/emerg.log
log-fail-file=/var/log/accel-ppp/auth-fail.log
copy=1
level=3

[sstp]
verbose=1
accept=ssl
ssl-pemfile=/etc/accel-ppp/sstp/server.pem
bind=0.0.0.0
port=$SSTP_PORT
ifname=sstp%d
ppp-max-mtu=1400
mppe=require

[ppp]
verbose=1
min-mtu=1280
mtu=1400
mru=1400
ccp=1
mppe=require
ipv4=require
ipv6=deny
lcp-echo-interval=20
lcp-echo-failure=3
lcp-echo-timeout=120

[client-ip-range]
disable

[ip-pool]
gw-ip-address=$SSTP_GW_IP
$SSTP_POOL

[dns]
dns1=1.1.1.1
dns2=8.8.8.8

[chap-secrets]
chap-secrets=/etc/accel-ppp/chap-secrets

[cli]
tcp=127.0.0.1:2001
EOF
}

write_secrets() {
  log "Writing /etc/accel-ppp/chap-secrets (user=$SSTP_USER)..."
  cat > /etc/accel-ppp/chap-secrets <<EOF
# user  server  password   ip
$SSTP_USER  *       $SSTP_PASS      *
EOF
  chmod 600 /etc/accel-ppp/chap-secrets
}

write_systemd() {
  log "Installing systemd unit..."
  install -m 644 "$REPO_DIR/accel-ppp.service" /etc/systemd/system/accel-ppp.service
  systemctl daemon-reload
}

setup_firewall() {
  log "Setting up firewall (iptables) and NAT for $SSTP_NET via $SSTP_WAN_IF..."
  sysctl -w net.ipv4.ip_forward=1 >/dev/null
  if ! grep -q "^net.ipv4.ip_forward=1" /etc/sysctl.conf; then
    echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
  fi

  iptables -C INPUT -p tcp --dport "$SSTP_PORT" -j ACCEPT 2>/dev/null \
    || iptables -I INPUT 1 -p tcp --dport "$SSTP_PORT" -j ACCEPT
  iptables -C FORWARD -i sstp+ -j ACCEPT 2>/dev/null \
    || iptables -I FORWARD 1 -i sstp+ -j ACCEPT
  iptables -C FORWARD -o sstp+ -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT 2>/dev/null \
    || iptables -I FORWARD 1 -o sstp+ -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
  iptables -t nat -C POSTROUTING -s "$SSTP_NET" -o "$SSTP_WAN_IF" -j MASQUERADE 2>/dev/null \
    || iptables -t nat -A POSTROUTING -s "$SSTP_NET" -o "$SSTP_WAN_IF" -j MASQUERADE
}

start_service() {
  log "Enabling and starting accel-ppp..."
  systemctl enable --now accel-ppp >/dev/null
  sleep 2
  systemctl --no-pager status accel-ppp | head -10
}

print_summary() {
  cat <<EOF


====================== SSTP ready ======================
  Server      : $SSTP_CN
  Port        : $SSTP_PORT/TCP
  Login       : $SSTP_USER
  Password    : $SSTP_PASS
  Tunnel net  : $SSTP_NET (gw $SSTP_GW_IP)
  WAN iface   : $SSTP_WAN_IF
  Cert        : /etc/accel-ppp/sstp/server.{crt,key,pem}
  Config      : /etc/accel-ppp.conf
  Users file  : /etc/accel-ppp/chap-secrets
  Logs        : /var/log/accel-ppp/accel-ppp.log
  Service     : systemctl status accel-ppp
  Sessions    : sudo accel-cmd show sessions

  Connect URL : sstp-test ssl://$SSTP_USER:$SSTP_PASS@$SSTP_CN:$SSTP_PORT
========================================================
EOF
}

main() {
  require_root
  install_build_deps
  build_accel_ppp
  generate_cert
  write_config
  write_secrets
  write_systemd
  setup_firewall
  start_service
  print_summary
}

main "$@"
